/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculatorproject;

/**
 *
 * @author allenhorton
 */
public class calculator_project extends javax.swing.JFrame {

    /**
     * Creates new form calculator_project
     */
    public calculator_project() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        txtResult = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnPlusMinus = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnMultiplication = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtResult, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 373, -1));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn1.setText("1");
        btn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn1MouseClicked(evt);
            }
        });
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel7.add(btn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 90, 66));

        btn4.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn4.setText("4");
        btn4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn4MouseClicked(evt);
            }
        });
        jPanel7.add(btn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 90, 66));

        btn7.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn7.setText("7");
        btn7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn7MouseClicked(evt);
            }
        });
        jPanel7.add(btn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 90, 66));

        btn0.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn0.setText("0");
        btn0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn0MouseClicked(evt);
            }
        });
        jPanel7.add(btn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 222, 90, 66));

        btn3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn3.setText("3");
        btn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn3MouseClicked(evt);
            }
        });
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel7.add(btn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 6, 90, 66));

        btn5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn5.setText("5");
        btn5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn5MouseClicked(evt);
            }
        });
        jPanel7.add(btn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 78, 90, 66));

        btn8.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn8.setText("8");
        btn8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn8MouseClicked(evt);
            }
        });
        jPanel7.add(btn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 150, 90, 66));

        btnPlusMinus.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnPlusMinus.setText("+/-");
        btnPlusMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusMinusActionPerformed(evt);
            }
        });
        jPanel7.add(btnPlusMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 222, 90, 66));

        btn2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn2.setText("2");
        btn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn2MouseClicked(evt);
            }
        });
        jPanel7.add(btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 6, 90, 66));

        btn6.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn6.setText("6");
        btn6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn6MouseClicked(evt);
            }
        });
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel7.add(btn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 78, 90, 66));

        btn9.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btn9.setText("9");
        btn9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn9MouseClicked(evt);
            }
        });
        jPanel7.add(btn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 150, 90, 66));

        btnClear.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnClear.setText("CE");
        btnClear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClearMouseClicked(evt);
            }
        });
        jPanel7.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 222, 90, 66));

        btnPlus.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnPlus.setText("+");
        btnPlus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPlusMouseClicked(evt);
            }
        });
        jPanel7.add(btnPlus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 6, 85, 54));

        btnMinus.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnMinus.setText("-");
        btnMinus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinusMouseClicked(evt);
            }
        });
        jPanel7.add(btnMinus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 66, 85, 54));

        btnMultiplication.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnMultiplication.setText("*");
        btnMultiplication.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMultiplicationMouseClicked(evt);
            }
        });
        btnMultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplicationActionPerformed(evt);
            }
        });
        jPanel7.add(btnMultiplication, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 126, 85, 50));

        btnDivision.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnDivision.setText("/");
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDivisionMouseClicked(evt);
            }
        });
        jPanel7.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 182, 85, 50));

        jButton17.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jButton17.setText("=");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });
        jPanel7.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 238, 85, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btnPlusMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusMinusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPlusMinusActionPerformed

    private void btnMultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMultiplicationActionPerformed

    private void btn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn1MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("1");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "1");
            value2 = Integer.parseInt(value2 + "1");
        }
        else 
            txtResult.setText(txtResult.getText() + "1");
    }//GEN-LAST:event_btn1MouseClicked

    private void btn2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn2MouseClicked
       String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("2");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "2");
            value2 = Integer.parseInt(value2 + "2");
        }
        else 
            txtResult.setText(txtResult.getText() + "2");
    }//GEN-LAST:event_btn2MouseClicked

    private void btn3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn3MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("3");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "3");
            value2 = Integer.parseInt(value2 + "3");
        }
        else 
            txtResult.setText(txtResult.getText() + "3");
    }//GEN-LAST:event_btn3MouseClicked

    private void btn4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn4MouseClicked
         String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("4");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "4");
            value2 = Integer.parseInt(value2 + "4");
        }
        else 
            txtResult.setText(txtResult.getText() + "4");
    }//GEN-LAST:event_btn4MouseClicked

    private void btn5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn5MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("5");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "5");
            value2 = Integer.parseInt(value2 + "5");
        }
        else 
            txtResult.setText(txtResult.getText() + "5");
    }//GEN-LAST:event_btn5MouseClicked

    private void btn6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn6MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("6");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "6");
            value2 = Integer.parseInt(value2 + "6");
        }
        else 
            txtResult.setText(txtResult.getText() + "6");
    }//GEN-LAST:event_btn6MouseClicked

    private void btn7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn7MouseClicked
       String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("7");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "7");
            value2 = Integer.parseInt(value2 + "7");
        }
        else 
            txtResult.setText(txtResult.getText() + "7");
    }//GEN-LAST:event_btn7MouseClicked

    private void btn8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn8MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("8");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "8");
            value2 = Integer.parseInt(value2 + "8");
        }
        else 
            txtResult.setText(txtResult.getText() + "8");
    }//GEN-LAST:event_btn8MouseClicked

    private void btn9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn9MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("9");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "9");
            value2 = Integer.parseInt(value2 + "9");
        }
        else 
            txtResult.setText(txtResult.getText() + "9");
    }//GEN-LAST:event_btn9MouseClicked

    private void btn0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn0MouseClicked
        String res = txtResult.getText();
        if(txtResult.getText().isEmpty())
            txtResult.setText("0");
        else if(res.contains("+") || res.contains("-") || res.contains("*") || res.contains("/")) 
        {
            txtResult.setText(txtResult.getText() + "0");
            value2 = Integer.parseInt(value2 + "0");
        }
        else 
            txtResult.setText(txtResult.getText() + "0");
    }//GEN-LAST:event_btn0MouseClicked

    private void btnClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClearMouseClicked
        txtResult.setText("");
    }//GEN-LAST:event_btnClearMouseClicked

    private void btnPlusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPlusMouseClicked
        if(txtResult.getText().isEmpty())
            return;
        else 
            value1 = Integer.parseInt(txtResult.getText());
            txtResult.setText(txtResult.getText() + " " + btnPlus.getText());
            operator = "plus";
    }//GEN-LAST:event_btnPlusMouseClicked

    private void btnMinusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinusMouseClicked
       if(txtResult.getText().isEmpty())
            return;
        else 
            value1 = Integer.parseInt(txtResult.getText());
            txtResult.setText(txtResult.getText() + " " + btnMinus.getText());
            operator = "minus";
    }//GEN-LAST:event_btnMinusMouseClicked

    private void btnMultiplicationMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMultiplicationMouseClicked
        if(txtResult.getText().isEmpty())
            return;
        else 
            value1 = Integer.parseInt(txtResult.getText());
            txtResult.setText(txtResult.getText() + " " + btnMultiplication.getText());
            operator = "multiplication";
    }//GEN-LAST:event_btnMultiplicationMouseClicked

    private void btnDivisionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseClicked
        if(txtResult.getText().isEmpty())
            return;
        else 
            value1 = Integer.parseInt(txtResult.getText());
            txtResult.setText(txtResult.getText() + " " + btnDivision.getText());
            operator = "division";
    }//GEN-LAST:event_btnDivisionMouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        double answer = 0;
        if(operator == "plus")
            answer = value1 + value2;
        else if(operator == "minus")
            answer = value1 - value2;
        else if (operator == "multiplication")
            answer = value1 * value2;
        else if (operator == "division")
            answer = value1/value2;
        
        String Result = Double.toString(answer);
        txtResult.setText(Result);
    }//GEN-LAST:event_jButton17MouseClicked

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculator_project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculator_project().setVisible(true);
            }
        });
    }
static int value1;
static int value2;
static String operator;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiplication;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPlusMinus;
    private javax.swing.JButton jButton17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField txtResult;
    // End of variables declaration//GEN-END:variables
}
